tasks:
  - init: |
      # Instala .NET SDK 9 só se ainda não estiver instalado
      if [ ! -d "$HOME/.dotnet" ]; then
        wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
        chmod +x /tmp/dotnet-install.sh
        /tmp/dotnet-install.sh --channel 9.0
      fi

      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools

      dotnet tool restore
      npm install
    command: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
      npm run start
